pipeline {
  agent any
    
  tools {nodejs "node"}
    
  stages {
        
    stage('Git') {
      steps {
        git 'https://github.com/doruboyina/screening.git'
      }
    }
     
    stage('Build') {
      steps {
         sh 'npm install'
         sh 'npm start'
         
      }
    }  
  }
}
